apiVersion: apps/v1
kind: Deployment
metadata: 
  name: conversor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversor
  template:  
    metadata: 
      name: conversor
      labels:
        app: conversor
    spec:
      containers:
      - name: site
        image: marciomoraeslima/conversao-temperatura:latest
        ports:
        - containerPort: 80   

---
apiVersion: v1
kind: Service
metadata: 
  name: conversor
spec:
  selector:
     app: conversor
  ports: 
    - port: 8080
      
      

 